version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-alura_loja}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    logging:
          options:
            max-size: 10m
            max-file: "3"
    volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"

  
  app:
    container_name: app-dev
    image: app-dev
    restart: always
    environment:
      POSTGRES_DRIVER_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST: localhost
      POSTGRES_DB: alura_loja
      POSTGRES_SSL_MODE: disable
    build:
        context: .
    volumes: 
      - .:/app
    ports:
      - 8080:8080
    depends_on: 
      - postgres



volumes:
    postgres:
    app:


